name: Node.js

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  test-node:
    name: Run Yespower Tests (Node.js)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./node

      - name: Run tests
        run: yarn test
        working-directory: ./node

      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
        working-directory: ./node

  test-wasm:
    name: Run Yespower Tests (WASM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./wasm

      - name: Run tests
        run: yarn test
        working-directory: ./wasm

      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
        working-directory: ./wasm
